#!/usr/bin/env python3

import re
import os
import argparse
from packaging.version import InvalidVersion, parse
import requests
import sys

PRG_NAME = "pkgsearch"
PRG_VERSION = "0.8"

# Only for debugging
DEBUG = False

# Last OpenBSD release
CURRENT_RELEASE = '7.4'

# Use the CDN mirror by default
MIRROR_URL = 'https://cdn.openbsd.org/pub/OpenBSD/'

CACHE_DIR = '{0}/.cache/{1}'.format(os.getenv('HOME'), PRG_NAME)

PKG_EMOJI = '\U0001F4E6'


def check_release(version: str):
    """Checks version for OpenBSD release."""
    try:
        parse(version)
    except InvalidVersion:
        return False

    # Check specific format major.minor for OpenBSD version
    m = re.match(r'^\d{1}.\d{1}$', version)
    if m is None:
        return False

    if (parse(version) > parse(CURRENT_RELEASE)) or (
        parse(version) < parse('2.0')
    ):
        return False

    return True


def create_cache_dir():
    try:
        os.makedirs(CACHE_DIR)
    except FileExistsError:
        if DEBUG:
            print("[INFO] cache directory already existing. Aborting creation.")

        return
    except OSError as e:
        print(f"[ERROR] unable to create cache directory {CACHE_DIR} - {e}")
        sys.exit(0)


def get_index(snapshot: bool, version: str, index_path: str, index_flag: bool):
    if snapshot:
        index_url = '{0}/snapshots/packages/amd64/index.txt'.format(MIRROR_URL)
    else:
        index_url = '{0}/{1}/packages/amd64/index.txt'.format(MIRROR_URL, version)

    if os.path.exists(index_path) and not index_flag:
        if DEBUG:
            print("[INFO] index file already existing. Aborting download.")

        return
    else:
        try:
            r = requests.get(index_url)
        except requests.exceptions.RequestException as e:
            print(f"[ERROR] unable to get INDEX file from URL - {e}")
            sys.exit(0)

        if r.status_code != 200:
            print(
                f"[ERROR] unable to get INDEX file from URL '{index_url}' - HTTP Status-Code = {r.status_code}"
            )
            sys.exit(0)
        else:
            try:
                with open(index_path, 'w') as out:
                    try:
                        out.write(r.text)
                    except (IOError, OSError):
                        print(f"[ERROR] Error writing to file {index_path}")
                        sys.exit(0)

            except (FileNotFoundError, PermissionError, OSError):
                print(f"[ERROR] Unable to open file {index_path} for writing")
                sys.exit(0)


def query_index(index_path: str, needle: str, emoji_flag: bool):
    try:
        f = open(index_path, 'r')
    except (FileNotFoundError, PermissionError, OSError):
        print(f"[ERROR] Unable to open file {index_path}")
        return

    while True:
        data = f.readline()

        if not data:
            break

        # Removing unneeded information like size and date
        # and convert list to string. Also, remove .tgz
        # extension from the package name/version
        pkg = ' '.join(data.split()[9:])[:-4]

        if re.findall(needle, pkg):
            # Get the size of the given package in bytes
            size_bytes = data.split()[4:5]

            # Convert to megabytes
            size_mbytes = int(size_bytes[0]) / 1048576

            if emoji_flag:
                # 57 was chosen since the longest str was 55 chars
                # This should cover every package name currently in
                # the OpenBSD repository
                print(
                    "{} {:<57} - Size: {:.2f}MB".format(
                        PKG_EMOJI, pkg, size_mbytes
                    )
                )
            else:
                print("{:<57} - Size: {:.2f}MB".format(pkg, size_mbytes))

    f.close()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("package")
    parser.add_argument(
        "-e", "--emoji", help="turn on emoji output", action="store_true"
    )
    parser.add_argument(
        "-i", "--index", help="download index", action="store_true"
    )

    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "-r",
        "--release",
        help=f"release to search for packages (default = {CURRENT_RELEASE})",
        default=CURRENT_RELEASE,
    )
    group.add_argument(
        "-s",
        "--snapshot",
        help="search for packages in snapshots",
        action="store_true"
    )

    parser.add_argument(
        "-v",
        "--version",
        help="display version",
        action="version",
        version=f"{PRG_NAME} {PRG_VERSION}",
    )

    args = parser.parse_args()

    if not check_release(args.release):
        print(f"[ERROR] invalid release '{args.release}'")
        sys.exit(0)

    if args.snapshot:
        index_path = '{0}/index-snapshots'.format(CACHE_DIR)
    else:
        index_path = '{0}/index-{1}'.format(CACHE_DIR, args.release)

    create_cache_dir()

    get_index(args.snapshot, args.release, index_path, args.index)

    if args.snapshot:
        print(f"Search packages '{args.package}' in snapshots")
    else:
        print(f"Search packages '{args.package}' for release {args.release}")
    query_index(index_path, args.package, args.emoji)


if __name__ == "__main__":
    main()
