[tool.black]
line-length = 80
skip-string-normalization = true
skip-magic-trailing-comma = false
target-version = ["py310"]

[tool.ruff]
line-length = 80
target-version = "py310"

[tool.ruff.format]
# leaves the quotes of all strings unchanged
quote-style = "preserve"
skip-magic-trailing-comma = false
